from . import account_account
from . import account_chart_template
from . import account_account_template
from . import account_fiscal_position
from . import account_fiscal_position_template
from . import account_journal
from . import account_move
from . import account_move_line
from . import res_company
from . import res_partner
from . import res_config_settings
